// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loan.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :exec
CALL create_loan(
    $1::UUID,
    $2::UUID,
    $3::NUMERIC,
    $4::NUMERIC,
    $5::INT
)
`

type CreateLoanParams struct {
	LoanID          uuid.UUID      `json:"loan_id"`
	CustomerID      uuid.UUID      `json:"customer_id"`
	PrincipalAmount pgtype.Numeric `json:"principal_amount"`
	InterestRate    pgtype.Numeric `json:"interest_rate"`
	Tenor           int32          `json:"tenor"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) error {
	_, err := q.db.Exec(ctx, createLoan,
		arg.LoanID,
		arg.CustomerID,
		arg.PrincipalAmount,
		arg.InterestRate,
		arg.Tenor,
	)
	return err
}

const getLoan = `-- name: GetLoan :one
SELECT id, customer_id, principal_amount, interest_rate, tenor, interest_amount, total_amount, paid_amount, status, start_date, created_at, updated_at
FROM loans
WHERE id = $1
`

func (q *Queries) GetLoan(ctx context.Context, id uuid.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.Tenor,
		&i.InterestAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
