// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Loan struct {
	ID              uuid.UUID          `json:"id"`
	CustomerID      uuid.UUID          `json:"customer_id"`
	PrincipalAmount pgtype.Numeric     `json:"principal_amount"`
	InterestRate    pgtype.Numeric     `json:"interest_rate"`
	Tenor           int32              `json:"tenor"`
	InterestAmount  pgtype.Numeric     `json:"interest_amount"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	PaidAmount      pgtype.Numeric     `json:"paid_amount"`
	Status          string             `json:"status"`
	StartDate       pgtype.Date        `json:"start_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
