// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repayment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRepayments = `-- name: CountRepayments :one
SELECT COUNT(*)
FROM repayments
WHERE loan_id = $1
`

func (q *Queries) CountRepayments(ctx context.Context, loanID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRepayments, loanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepayment = `-- name: CreateRepayment :exec
CALL create_repayment(
    $1::UUID,
    $2::UUID,
    $3::NUMERIC
)
`

type CreateRepaymentParams struct {
	RepaymentID uuid.UUID      `json:"repayment_id"`
	LoanID      uuid.UUID      `json:"loan_id"`
	Amount      pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateRepayment(ctx context.Context, arg CreateRepaymentParams) error {
	_, err := q.db.Exec(ctx, createRepayment, arg.RepaymentID, arg.LoanID, arg.Amount)
	return err
}

const getRepayment = `-- name: GetRepayment :one
SELECT id, loan_id, amount, payment_date, created_at, updated_at
FROM repayments
WHERE id = $1
`

func (q *Queries) GetRepayment(ctx context.Context, id uuid.UUID) (Repayment, error) {
	row := q.db.QueryRow(ctx, getRepayment, id)
	var i Repayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Amount,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepayments = `-- name: ListRepayments :many
SELECT id, loan_id, amount, payment_date, created_at, updated_at
FROM repayments
WHERE loan_id = $1
ORDER BY payment_date DESC, created_at DESC
LIMIT $2
OFFSET $3
`

type ListRepaymentsParams struct {
	LoanID uuid.UUID `json:"loan_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRepayments(ctx context.Context, arg ListRepaymentsParams) ([]Repayment, error) {
	rows, err := q.db.Query(ctx, listRepayments, arg.LoanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repayment
	for rows.Next() {
		var i Repayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Amount,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
